[package]
name = "citadel-assignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
citadel_sdk = "0.5.0"
futures = "0.3.28"
tokio = "1.28.0"
